name: Build and Deploy Cactus

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: uorux-scale-set
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix cachix installer
        run: sudo apt update && sudo apt install -y lzma xz-utils

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Log in to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.rooty.dev
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        run: |
          # streamLayeredImage produces an executable script that streams to docker
          nix run .#dockerImage | docker load
          
          # Tag the image for Gitea registry
          docker tag astro-cactus:latest gitea.rooty.dev/jrt/cactus:latest
          docker tag astro-cactus:latest gitea.rooty.dev/jrt/cactus:${{ github.sha }}
          
          # Push both tags
          docker push gitea.rooty.dev/jrt/cactus:latest
          docker push gitea.rooty.dev/jrt/cactus:${{ github.sha }}

      - name: Setup kubectl
        if: github.ref == 'refs/heads/main'
        uses: azure/setup-kubectl@v3
        id: install

      - name: Restart deployment
        if: github.ref == 'refs/heads/main'
        run: kubectl rollout restart deployment personal-site --namespace personal-site
